"""changed database

Revision ID: 5bc409445cd9
Revises: 8767a9993283
Create Date: 2025-05-14 23:19:47.195216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc409445cd9'
down_revision: Union[str, None] = '8767a9993283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminuser',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminuser_email'), 'adminuser', ['email'], unique=True)
    op.create_index(op.f('ix_adminuser_id'), 'adminuser', ['id'], unique=False)
    op.create_index(op.f('ix_adminuser_username'), 'adminuser', ['username'], unique=True)
    op.create_table('apikey',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_id'), 'apikey', ['id'], unique=False)
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=True)
    op.create_table('faissmetadata',
    sa.Column('faiss_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('book', sa.String(), nullable=False),
    sa.Column('title_group', sa.String(), nullable=False),
    sa.Column('chapter', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faissmetadata_faiss_id'), 'faissmetadata', ['faiss_id'], unique=True)
    op.create_index(op.f('ix_faissmetadata_id'), 'faissmetadata', ['id'], unique=False)
    op.create_index(op.f('ix_faissmetadata_title'), 'faissmetadata', ['title'], unique=False)
    op.create_table('usagelog',
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['apikey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usagelog_id'), 'usagelog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usagelog_id'), table_name='usagelog')
    op.drop_table('usagelog')
    op.drop_index(op.f('ix_faissmetadata_title'), table_name='faissmetadata')
    op.drop_index(op.f('ix_faissmetadata_id'), table_name='faissmetadata')
    op.drop_index(op.f('ix_faissmetadata_faiss_id'), table_name='faissmetadata')
    op.drop_table('faissmetadata')
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_id'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_adminuser_username'), table_name='adminuser')
    op.drop_index(op.f('ix_adminuser_id'), table_name='adminuser')
    op.drop_index(op.f('ix_adminuser_email'), table_name='adminuser')
    op.drop_table('adminuser')
    # ### end Alembic commands ###
